import z from "zod"
import { Tool } from "../tool"
import type { Finding, HookResult } from "./shared"

import {
  entraEnum,
  vmEnum,
  aksEnum,
  nsgAudit,
  rbacAudit,
  sqlEnumAzure,
  appServiceEnum,
  subscriptionEnum,
  resourceGraph,
  vnetEnum,
  dnsEnum,
  acrEnum,
  vmssEnum,
  redisEnum,
  dataFactoryEnum,
  frontDoorEnum,
  containerInstanceEnum,
  apimEnum,
  databricksEnum,
  appInsightsEnum,
  monitorEnum,
  recoveryVaultEnum,
  intuneEnum,
  graphUserEnum,
  appRegistrationEnum,
  logicAppConnectorEnum,
  automationRunbookEnum,
  synapseEnum,
  purviewEnum,
  subdomainTakeover,
  stalePermissionAudit,
  publicExposureScan,
  databricksSecretDump,
  cognitiveServicesEnum,
  iotHubEnum,
  signalrEnum,
  eventGridEnum,
  batchEnum,
  mapsSearchEnum,
  sentinelEnum,
  vpnGatewayEnum,
  expressRouteEnum,
  privateLinkAudit,
  serviceFabricEnum,
  batchAccountEnum,
  managedEnvEnum,
  staticWebAppEnum,
} from "./recon"
import {
  keyvaultDump,
  managedIdentity,
  azureadToken,
  imdsHarvest,
  deviceCodePhish,
  tokenTheft,
  certificateAbuse,
  storageKeyDump,
  automationCredDump,
  graphTokenHarvest,
  refreshTokenReplay,
  runbookCredExtract,
  kubeconfigDump,
  webappEnvDump,
} from "./credential"
import {
  entraPrivesc,
  customRoleExploit,
  conditionalAccessAudit,
  pimAbuse,
  managedIdentityPrivesc,
  deploymentPrivesc,
  globalAdminElevate,
  appAdminPrivesc,
  resourceHierarchyAbuse,
  groupMembershipAbuse,
  partnerAdminAbuse,
} from "./privesc"
import {
  runbookBackdoor,
  logicAppBackdoor,
  functionAppBackdoor,
  spPersist,
  vmExtensionBackdoor,
  webhookPersist,
  devopsPipelineBackdoor,
  lighthousePersist,
  acrImageBackdoor,
  scheduledTaskPersist,
  oauthAppPersist,
} from "./persistence"
import {
  vmRunCommand,
  bastionTunnel,
  arcExec,
  devopsServiceConn,
  crossTenantEnum,
  customScriptExt,
  userdataCommand,
  intuneDeploy,
  msbuildExec,
  sharedImageInject,
} from "./lateral"
import {
  diagnosticTamper,
  sentinelSuppress,
  defenderDisable,
  activityLogTamper,
  policyExempt,
  wafBypass,
  alertSuppress,
  logAnalyticsTamper,
  nsgFlowLogDisable,
  resourceMove,
  tagManipulation,
} from "./evasion"
import {
  storageDump,
  cosmosDump,
  diskSnapshot,
  tableQueueDump,
  fileShareDump,
  dataLakeDump,
  serviceBusSniff,
  eventHubTap,
  graphMailDump,
  sharepointDump,
  teamsDump,
  vmDiskDownload,
} from "./exfil"
import {
  defenderPlanAudit,
  defenderContactAudit,
  storageSecurityAudit,
  sqlAuditConfig,
  postgresAudit,
  mysqlAudit,
  cosmosSecurityAudit,
  diagnosticAudit,
  activityAlertAudit,
  networkWatcherAudit,
  vmSecurityAudit,
  appserviceSecurityAudit,
  keyvaultSecurityAudit,
  identityMfaAudit,
  guestAccessAudit,
  passwordPolicyAudit,
  resourceLockAudit,
  policyComplianceAudit,
} from "./compliance"
import {
  federationBackdoor,
  ptaAbuse,
  aadconnectDump,
  seamlessSsoAbuse,
  samlForge,
  mfaManipulation,
  userCreation,
  passwordSpray,
  tenantReconInsider,
  consentPhish,
} from "./identity"
import { resourceHijack, dataDestroy, ransomwareSim, accountLockout, serviceDisruption } from "./impact"
import { exchangeAbuse, sharepointEnum, teamsEnum, onedriveAccess } from "./m365"
import { cleanupAzure } from "./cleanup"

const PROGRAMS = {
  subscription_enum: {
    description: "Enumerate all accessible Azure subscriptions, management groups, and tenant info",
    args: "",
  },
  resource_graph: {
    description: "Azure Resource Graph cross-subscription discovery",
    args: "[--query QUERY] [--subscription-id SUB]",
  },
  entra_enum: {
    description: "Enumerate Entra ID users, groups, app registrations, SPs, role assignments",
    args: "[--subscription-id SUB]",
  },
  vm_enum: {
    description: "Enumerate Azure VMs: extensions, custom data, disk encryption, public IPs",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  vmss_enum: {
    description: "Enumerate VM Scale Sets: instances, extensions, managed identity",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  aks_enum: {
    description: "Enumerate AKS clusters: config, node pools, RBAC, admin credentials",
    args: "[--cluster NAME] [--resource-group RG]",
  },
  vnet_enum: {
    description: "VNet topology: subnets, peering, VPN gateways, ExpressRoute",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  nsg_audit: {
    description: "Audit NSGs: open ingress, any-any rules, dangerous port exposure",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  rbac_audit: {
    description: "Audit RBAC: Owner/Contributor at sub level, dangerous custom roles",
    args: "[--subscription-id SUB]",
  },
  sql_enum: {
    description: "Enumerate Azure SQL: firewall, AD admin, TDE, auditing",
    args: "[--subscription-id SUB] [--server NAME]",
  },
  app_service_enum: {
    description: "Enumerate App Services: connection strings, secrets, SCM access",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  dns_enum: {
    description: "Azure DNS zones, records, dangling CNAMEs for subdomain takeover",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  acr_enum: {
    description: "Azure Container Registry: repos, admin credentials, public access",
    args: "[--subscription-id SUB]",
  },
  redis_enum: {
    description: "Azure Redis: access keys, firewall, TLS, public network access",
    args: "[--subscription-id SUB]",
  },
  data_factory_enum: {
    description: "Data Factory: pipelines, linked services, connection strings",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  front_door_enum: {
    description: "Front Door / WAF: origins, routing, WAF policies, exclusions",
    args: "[--subscription-id SUB]",
  },
  container_instance_enum: {
    description: "Container Instances: env vars, mounted volumes, identity",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  apim_enum: {
    description: "API Management: APIs, subscriptions, named values (secrets)",
    args: "[--subscription-id SUB]",
  },
  databricks_enum: {
    description: "Databricks workspaces: clusters, notebooks, jobs, secrets",
    args: "[--subscription-id SUB]",
  },
  app_insights_enum: {
    description: "Application Insights: instrumentation keys, connection strings",
    args: "[--subscription-id SUB]",
  },
  monitor_enum: {
    description: "Azure Monitor: Log Analytics, alert rules, diagnostics, retention",
    args: "[--subscription-id SUB]",
  },
  recovery_vault_enum: {
    description: "Recovery Services vaults: backup policies, soft delete status",
    args: "[--subscription-id SUB]",
  },
  intune_enum: { description: "Intune managed devices via Graph: compliance, OS, last sync", args: "" },
  graph_user_enum: {
    description: "Deep Entra user enum: account status, guests, stale accounts",
    args: "[--filter FILTER]",
  },
  app_registration_enum: { description: "App registrations: expiring credentials, overprivileged perms", args: "" },
  logic_app_connector_enum: {
    description: "Logic App API connections — credential stores",
    args: "[--subscription-id SUB]",
  },
  automation_runbook_enum: {
    description: "Automation Accounts and runbooks: schedules, history",
    args: "[--subscription-id SUB]",
  },
  synapse_enum: {
    description: "Synapse Analytics: SQL pools, Spark pools, linked services",
    args: "[--subscription-id SUB]",
  },
  purview_enum: {
    description: "Microsoft Purview: data governance, classification rules",
    args: "[--subscription-id SUB]",
  },
  subdomain_takeover: {
    description: "Check dangling DNS CNAMEs for subdomain takeover",
    args: "[--subscription-id SUB]",
  },
  stale_permission_audit: {
    description: "Find RBAC assignments for deleted/disabled principals",
    args: "[--subscription-id SUB]",
  },
  public_exposure_scan: {
    description: "Enumerate public-facing resources: IPs, open NSGs, storage",
    args: "[--subscription-id SUB]",
  },
  databricks_secret_dump: {
    description: "Extract Databricks workspace secrets via REST API",
    args: "[--workspace-url URL]",
  },
  cognitive_services_enum: {
    description: "Cognitive Services: API keys, endpoint access",
    args: "[--subscription-id SUB]",
  },
  iot_hub_enum: {
    description: "IoT Hubs: shared access policies, device count, routing",
    args: "[--subscription-id SUB]",
  },
  signalr_enum: { description: "SignalR Service: access keys, network rules", args: "[--subscription-id SUB]" },
  event_grid_enum: { description: "Event Grid topics: subscriptions, endpoints", args: "[--subscription-id SUB]" },
  batch_enum: { description: "Batch accounts: pools, auto-storage, keys", args: "[--subscription-id SUB]" },
  maps_search_enum: { description: "Azure Maps accounts: key-based auth, usage tier", args: "[--subscription-id SUB]" },
  sentinel_enum: {
    description: "Sentinel: data connectors, analytics rules, incidents",
    args: "[--subscription-id SUB]",
  },
  vpn_gateway_enum: {
    description: "VPN gateways: connections, shared keys, BGP config",
    args: "[--subscription-id SUB]",
  },
  express_route_enum: {
    description: "ExpressRoute circuits: peerings, providers, auth keys",
    args: "[--subscription-id SUB]",
  },
  private_link_audit: {
    description: "Private Endpoints and Private Link: connection status, DNS",
    args: "[--subscription-id SUB]",
  },
  service_fabric_enum: {
    description: "Service Fabric clusters: node types, apps, health, security config",
    args: "[--subscription-id SUB]",
  },
  batch_account_enum: {
    description: "Batch accounts: pools, jobs, keys, network config",
    args: "[--subscription-id SUB]",
  },
  managed_env_enum: {
    description: "Container Apps environments: apps, secrets, ingress, scaling",
    args: "[--subscription-id SUB]",
  },
  static_web_app_enum: {
    description: "Static Web Apps: custom domains, auth, linked APIs",
    args: "[--subscription-id SUB]",
  },
  keyvault_dump: {
    description: "Extract secrets, keys, certificates from Key Vaults",
    args: "[--vault-name NAME] [--subscription-id SUB]",
  },
  managed_identity: {
    description: "Extract managed identity OAuth tokens via IMDS",
    args: "[--resource RESOURCE_URL]",
  },
  azuread_token: {
    description: "Manipulate Azure AD tokens: refresh exchange, FOCI abuse",
    args: "--action <refresh|foci> [--refresh-token TOKEN] [--client-id ID]",
  },
  imds_harvest: { description: "Extract credentials and metadata from Azure IMDS", args: "[--resource RESOURCE_URL]" },
  device_code_phish: {
    description: "Device code auth flow for phishing",
    args: "[--client-id ID] [--scope SCOPE] [--tenant TENANT]",
  },
  token_theft: { description: "Extract Azure tokens from local files", args: "" },
  certificate_abuse: {
    description: "Generate/upload certificate for SP auth — bypasses MFA",
    args: "--app-id ID [--generate] [--subscription-id SUB]",
  },
  storage_key_dump: {
    description: "Extract storage account access keys and SAS tokens",
    args: "[--account-name NAME] [--subscription-id SUB]",
  },
  automation_cred_dump: {
    description: "Extract credentials from Automation Accounts",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  graph_token_harvest: { description: "Harvest tokens for Graph, ARM, Key Vault, SQL, Storage", args: "" },
  refresh_token_replay: { description: "Check token policies and attempt refresh token replay", args: "" },
  runbook_cred_extract: {
    description: "Extract hardcoded credentials from runbook source",
    args: "[--subscription-id SUB]",
  },
  kubeconfig_dump: {
    description: "Extract AKS kubeconfig for all accessible clusters",
    args: "[--subscription-id SUB]",
  },
  webapp_env_dump: {
    description: "Dump web app env vars — passwords, API keys, secrets",
    args: "[--subscription-id SUB]",
  },
  entra_privesc: {
    description: "Exploit Entra ID misconfigs for privilege escalation",
    args: "--method <consent_grant|sp_secret|role_assign> [--target-id ID]",
  },
  custom_role_exploit: {
    description: "Find custom RBAC roles with dangerous actions",
    args: "[--subscription-id SUB]",
  },
  conditional_access_audit: { description: "Enumerate CA policies — find MFA gaps, excluded users", args: "" },
  pim_abuse: {
    description: "Enumerate PIM eligible roles — no approval required",
    args: "[--role-id ID] [--activate]",
  },
  managed_identity_privesc: { description: "Find over-privileged managed identities", args: "[--subscription-id SUB]" },
  deployment_privesc: {
    description: "Abuse deployments/write for Owner role assignment",
    args: "[--subscription-id SUB] [--resource-group RG]",
  },
  global_admin_elevate: { description: "Attempt Global Administrator elevation", args: "" },
  app_admin_privesc: { description: "Find owned apps with high-privilege API permissions", args: "" },
  resource_hierarchy_abuse: { description: "Enumerate management groups for hierarchy abuse", args: "" },
  group_membership_abuse: { description: "Find dynamic groups with exploitable membership rules", args: "" },
  partner_admin_abuse: { description: "Enumerate partner/delegated admin relationships", args: "" },
  runbook_backdoor: {
    description: "Create/modify Automation runbook with reverse shell",
    args: "--automation-account NAME --resource-group RG [--callback-url URL]",
  },
  logic_app_backdoor: {
    description: "Inject webhook trigger into Logic App",
    args: "--resource-group RG --name NAME --callback-url URL [--method create|inject]",
  },
  function_app_backdoor: {
    description: "Deploy Function App with reverse shell",
    args: "--resource-group RG --name NAME --callback-url URL [--trigger http|timer]",
  },
  sp_persist: {
    description: "Create app registration with client secret for persistence",
    args: "--name NAME [--role ROLE] [--scope SCOPE]",
  },
  vm_extension_backdoor: {
    description: "Deploy Custom Script Extension on VMs",
    args: "--vm-name VM --resource-group RG --command CMD [--os windows|linux]",
  },
  webhook_persist: {
    description: "Create Event Grid subscription with webhook",
    args: "--endpoint URL [--event-type TYPE] [--subscription-id SUB]",
  },
  devops_pipeline_backdoor: {
    description: "Inject steps into Azure DevOps pipeline",
    args: "--org ORG --project PROJECT [--pipeline-id ID] [--callback-url URL]",
  },
  lighthouse_persist: {
    description: "Create Lighthouse delegation to external tenant",
    args: "--tenant-id TENANT --principal-id PRINCIPAL [--role ROLE]",
  },
  acr_image_backdoor: {
    description: "Backdoor ACR container images",
    args: "--registry REGISTRY --image IMAGE [--callback-url URL]",
  },
  scheduled_task_persist: {
    description: "Create scheduled tasks via VM Run Command",
    args: "--vm-name VM --resource-group RG --command CMD [--schedule CRON]",
  },
  oauth_app_persist: {
    description: "Create OAuth app with long-lived refresh tokens",
    args: "--name NAME [--redirect-uri URI]",
  },
  vm_run_command: {
    description: "Execute commands on VMs via Run Command API",
    args: "--vm-name VM --resource-group RG --cmd CMD [--os windows|linux]",
  },
  bastion_tunnel: {
    description: "Enumerate Bastion hosts, create SSH/RDP tunnels",
    args: "[--resource-group RG] [--target-vm VM] [--ssh-key KEY]",
  },
  arc_exec: {
    description: "Execute commands on Arc-connected machines",
    args: "[--machine-name NAME] [--resource-group RG] [--cmd CMD]",
  },
  devops_service_conn: { description: "Enumerate DevOps service connections", args: "--org ORG --project PROJECT" },
  cross_tenant_enum: { description: "Enumerate cross-tenant access settings, B2B", args: "" },
  custom_script_ext: {
    description: "Deploy Custom Script Extension to VMs",
    args: "--vm-name VM --resource-group RG --script-url URL",
  },
  userdata_command: {
    description: "Inject commands via VM user data",
    args: "--vm-name VM --resource-group RG --command CMD",
  },
  intune_deploy: {
    description: "Deploy scripts/apps to Intune-managed devices",
    args: "[--script-path PATH] [--target-group GROUP]",
  },
  msbuild_exec: {
    description: "Execute code via MSBuild on Windows VMs",
    args: "--vm-name VM --resource-group RG --payload-url URL",
  },
  shared_image_inject: {
    description: "Inject into Shared Image Gallery",
    args: "--gallery GALLERY --image IMAGE --resource-group RG",
  },
  diagnostic_tamper: {
    description: "Manipulate diagnostic settings and activity logs",
    args: "--action <status|disable> [--subscription-id SUB] [--resource-id RID]",
  },
  sentinel_suppress: {
    description: "Suppress/close Sentinel incidents, disable rules",
    args: "--action <list|close|disable_rule> [--subscription-id SUB] [--workspace WS]",
  },
  defender_disable: { description: "Disable Defender for Cloud plans", args: "[--plan PLAN] [--subscription-id SUB]" },
  activity_log_tamper: {
    description: "Modify Activity Log diagnostic settings",
    args: "--action <status|delete|redirect> [--subscription-id SUB]",
  },
  policy_exempt: {
    description: "Create Azure Policy exemptions",
    args: "--assignment ASSIGNMENT --name NAME [--subscription-id SUB]",
  },
  waf_bypass: {
    description: "Modify/disable WAF policies",
    args: "--action <list|disable|exclude> [--subscription-id SUB]",
  },
  alert_suppress: {
    description: "Suppress Azure Monitor alerts",
    args: "--action <list|disable|suppress> [--subscription-id SUB]",
  },
  log_analytics_tamper: {
    description: "Tamper with Log Analytics workspace",
    args: "[--subscription-id SUB] [--workspace WS]",
  },
  nsg_flow_log_disable: { description: "Disable NSG flow logs", args: "[--subscription-id SUB] [--location LOCATION]" },
  resource_move: {
    description: "Move resources between RGs to evade monitoring",
    args: "--source-rg RG --target-rg RG --resource-id RID",
  },
  tag_manipulation: {
    description: "Manipulate resource tags to evade policies",
    args: "[--subscription-id SUB] [--resource-id RID]",
  },
  storage_dump: {
    description: "Enumerate and download from Azure Blob Storage",
    args: "[--account-name NAME] [--container CONTAINER] [--download]",
  },
  cosmos_dump: {
    description: "Enumerate and extract data from Cosmos DB",
    args: "--account NAME [--database DB] [--container CONTAINER]",
  },
  disk_snapshot: {
    description: "Create managed disk snapshots for offline analysis",
    args: "--disk-id DISK_ID --resource-group RG [--share-sub SUB]",
  },
  table_queue_dump: {
    description: "Extract from Table Storage and Queue Storage",
    args: "--account-name NAME [--table TABLE] [--queue QUEUE]",
  },
  file_share_dump: {
    description: "Enumerate and download from Azure File Shares",
    args: "--account-name NAME [--share SHARE] [--pattern REGEX]",
  },
  data_lake_dump: {
    description: "Enumerate and extract from Data Lake Gen2",
    args: "--account-name NAME [--filesystem FS] [--path PATH]",
  },
  service_bus_sniff: {
    description: "Peek Service Bus messages without consuming",
    args: "[--namespace NS] [--queue QUEUE] [--subscription-id SUB]",
  },
  event_hub_tap: {
    description: "Enumerate Event Hubs, capture event streams",
    args: "[--namespace NS] [--eventhub HUB] [--subscription-id SUB]",
  },
  graph_mail_dump: {
    description: "Dump email via Graph API — mailbox, forwarding rules",
    args: "[--user USER] [--folder FOLDER] [--search QUERY] [--limit N]",
  },
  sharepoint_dump: {
    description: "Dump SharePoint sites and OneDrive libraries",
    args: "[--site SITE_ID] [--search QUERY] [--limit N]",
  },
  teams_dump: {
    description: "Dump Teams data — channels, messages, files",
    args: "[--team TEAM_ID] [--channel CHANNEL_ID] [--limit N]",
  },
  vm_disk_download: {
    description: "Snapshot VM disk and generate SAS download URL",
    args: "[--disk DISK] [--resource-group RG] [--execute]",
  },
  defender_plan_audit: { description: "CIS 2.1: Audit Defender plans", args: "[--subscription-id SUB]" },
  defender_contact_audit: {
    description: "CIS 2.1.21: Verify Defender security contacts",
    args: "[--subscription-id SUB]",
  },
  storage_security_audit: { description: "CIS 3.x: Storage security audit", args: "[--subscription-id SUB]" },
  sql_audit_config: { description: "CIS 4.1-4.2: SQL server security audit", args: "[--subscription-id SUB]" },
  postgres_audit: { description: "CIS 4.3: PostgreSQL security audit", args: "[--subscription-id SUB]" },
  mysql_audit: { description: "CIS 4.4: MySQL security audit", args: "[--subscription-id SUB]" },
  cosmos_security_audit: { description: "CIS 4.5: Cosmos DB security audit", args: "[--subscription-id SUB]" },
  diagnostic_audit: { description: "CIS 5.1: Audit diagnostic settings", args: "[--subscription-id SUB]" },
  activity_alert_audit: { description: "CIS 5.2: Verify activity log alerts", args: "[--subscription-id SUB]" },
  network_watcher_audit: { description: "CIS 6.5: Verify Network Watcher", args: "[--subscription-id SUB]" },
  vm_security_audit: { description: "CIS 7.x: VM security audit", args: "[--subscription-id SUB]" },
  appservice_security_audit: { description: "CIS 9.x: App Service security audit", args: "[--subscription-id SUB]" },
  keyvault_security_audit: { description: "CIS 8.x: Key Vault security audit", args: "[--subscription-id SUB]" },
  identity_mfa_audit: { description: "CIS 1.1-1.3: Identity MFA audit", args: "" },
  guest_access_audit: { description: "CIS 1.5: Guest user access audit", args: "" },
  password_policy_audit: { description: "CIS 1.8-1.11: Password policies audit", args: "" },
  resource_lock_audit: { description: "CIS 8.5: Resource locks audit", args: "[--subscription-id SUB]" },
  policy_compliance_audit: { description: "Audit Azure Policy compliance", args: "[--subscription-id SUB]" },
  federation_backdoor: {
    description: "Enumerate/add federation trusts for Golden SAML",
    args: "[--domain DOMAIN] [--idp-url URL]",
  },
  pta_abuse: { description: "Enumerate PTA agents for credential interception", args: "" },
  aadconnect_dump: { description: "Enumerate AADConnect sync accounts", args: "" },
  seamless_sso_abuse: { description: "Check Seamless SSO for silver ticket attack", args: "" },
  saml_forge: { description: "Enumerate SAML config for Golden SAML", args: "[--domain DOMAIN]" },
  mfa_manipulation: { description: "Enumerate MFA methods, find users without MFA", args: "[--user USER]" },
  user_creation: {
    description: "Create rogue users or service principals",
    args: "[--upn USER@DOMAIN] [--password PASS] [--role ROLE] [--service-principal]",
  },
  password_spray: {
    description: "Azure AD password spray with lockout detection",
    args: "[--user USER] [--username-list FILE] [--password PASS] [--tenant TENANT]",
  },
  tenant_recon_insider: { description: "Full insider tenant recon — org, users, admins", args: "" },
  consent_phish: {
    description: "Illicit consent grant / OAuth phishing",
    args: "[--name NAME] [--redirect-uri URI] [--tenant TENANT] [--create]",
  },
  resource_hijack: { description: "Hijack resources for cryptomining", args: "[--subscription-id SUB] [--execute]" },
  data_destroy: { description: "Data destruction assessment", args: "[--subscription-id SUB] [--execute]" },
  ransomware_sim: {
    description: "Ransomware simulation — rotate keys, delete backups",
    args: "[--subscription-id SUB] [--execute]",
  },
  account_lockout: { description: "Account lockout assessment", args: "[--target USER]" },
  service_disruption: { description: "Service disruption assessment", args: "[--subscription-id SUB] [--execute]" },
  exchange_abuse: {
    description: "Exchange Online abuse — delegation, forwarding",
    args: "[--user USER] [--action enum|forward|delegate]",
  },
  sharepoint_enum: { description: "SharePoint Online enumeration", args: "[--site SITE]" },
  teams_enum: { description: "Microsoft Teams enumeration", args: "[--team TEAM_ID]" },
  onedrive_access: { description: "OneDrive access — drives, shared files", args: "[--user USER]" },
  cleanup_azure: {
    description: "Remove all CyberStrike-created Azure resources. ALWAYS run before leaving",
    args: "[--dry-run]",
  },
} as const satisfies Record<string, { description: string; args: string }>

type Program = keyof typeof PROGRAMS

const dispatch: Record<Program, (args: string[], timeout: number) => Promise<HookResult>> = {
  subscription_enum: subscriptionEnum,
  resource_graph: resourceGraph,
  entra_enum: entraEnum,
  vm_enum: vmEnum,
  vmss_enum: vmssEnum,
  aks_enum: aksEnum,
  vnet_enum: vnetEnum,
  nsg_audit: nsgAudit,
  rbac_audit: rbacAudit,
  sql_enum: sqlEnumAzure,
  app_service_enum: appServiceEnum,
  dns_enum: dnsEnum,
  acr_enum: acrEnum,
  redis_enum: redisEnum,
  data_factory_enum: dataFactoryEnum,
  front_door_enum: frontDoorEnum,
  container_instance_enum: containerInstanceEnum,
  apim_enum: apimEnum,
  databricks_enum: databricksEnum,
  app_insights_enum: appInsightsEnum,
  monitor_enum: monitorEnum,
  recovery_vault_enum: recoveryVaultEnum,
  intune_enum: intuneEnum,
  graph_user_enum: graphUserEnum,
  app_registration_enum: appRegistrationEnum,
  logic_app_connector_enum: logicAppConnectorEnum,
  automation_runbook_enum: automationRunbookEnum,
  synapse_enum: synapseEnum,
  purview_enum: purviewEnum,
  subdomain_takeover: subdomainTakeover,
  stale_permission_audit: stalePermissionAudit,
  public_exposure_scan: publicExposureScan,
  databricks_secret_dump: databricksSecretDump,
  cognitive_services_enum: cognitiveServicesEnum,
  iot_hub_enum: iotHubEnum,
  signalr_enum: signalrEnum,
  event_grid_enum: eventGridEnum,
  batch_enum: batchEnum,
  maps_search_enum: mapsSearchEnum,
  sentinel_enum: sentinelEnum,
  vpn_gateway_enum: vpnGatewayEnum,
  express_route_enum: expressRouteEnum,
  private_link_audit: privateLinkAudit,
  service_fabric_enum: serviceFabricEnum,
  batch_account_enum: batchAccountEnum,
  managed_env_enum: managedEnvEnum,
  static_web_app_enum: staticWebAppEnum,
  keyvault_dump: keyvaultDump,
  managed_identity: managedIdentity,
  azuread_token: azureadToken,
  imds_harvest: imdsHarvest,
  device_code_phish: deviceCodePhish,
  token_theft: tokenTheft,
  certificate_abuse: certificateAbuse,
  storage_key_dump: storageKeyDump,
  automation_cred_dump: automationCredDump,
  graph_token_harvest: graphTokenHarvest,
  refresh_token_replay: refreshTokenReplay,
  runbook_cred_extract: runbookCredExtract,
  kubeconfig_dump: kubeconfigDump,
  webapp_env_dump: webappEnvDump,
  entra_privesc: entraPrivesc,
  custom_role_exploit: customRoleExploit,
  conditional_access_audit: conditionalAccessAudit,
  pim_abuse: pimAbuse,
  managed_identity_privesc: managedIdentityPrivesc,
  deployment_privesc: deploymentPrivesc,
  global_admin_elevate: globalAdminElevate,
  app_admin_privesc: appAdminPrivesc,
  resource_hierarchy_abuse: resourceHierarchyAbuse,
  group_membership_abuse: groupMembershipAbuse,
  partner_admin_abuse: partnerAdminAbuse,
  runbook_backdoor: runbookBackdoor,
  logic_app_backdoor: logicAppBackdoor,
  function_app_backdoor: functionAppBackdoor,
  sp_persist: spPersist,
  vm_extension_backdoor: vmExtensionBackdoor,
  webhook_persist: webhookPersist,
  devops_pipeline_backdoor: devopsPipelineBackdoor,
  lighthouse_persist: lighthousePersist,
  acr_image_backdoor: acrImageBackdoor,
  scheduled_task_persist: scheduledTaskPersist,
  oauth_app_persist: oauthAppPersist,
  vm_run_command: vmRunCommand,
  bastion_tunnel: bastionTunnel,
  arc_exec: arcExec,
  devops_service_conn: devopsServiceConn,
  cross_tenant_enum: crossTenantEnum,
  custom_script_ext: customScriptExt,
  userdata_command: userdataCommand,
  intune_deploy: intuneDeploy,
  msbuild_exec: msbuildExec,
  shared_image_inject: sharedImageInject,
  diagnostic_tamper: diagnosticTamper,
  sentinel_suppress: sentinelSuppress,
  defender_disable: defenderDisable,
  activity_log_tamper: activityLogTamper,
  policy_exempt: policyExempt,
  waf_bypass: wafBypass,
  alert_suppress: alertSuppress,
  log_analytics_tamper: logAnalyticsTamper,
  nsg_flow_log_disable: nsgFlowLogDisable,
  resource_move: resourceMove,
  tag_manipulation: tagManipulation,
  storage_dump: storageDump,
  cosmos_dump: cosmosDump,
  disk_snapshot: diskSnapshot,
  table_queue_dump: tableQueueDump,
  file_share_dump: fileShareDump,
  data_lake_dump: dataLakeDump,
  service_bus_sniff: serviceBusSniff,
  event_hub_tap: eventHubTap,
  graph_mail_dump: graphMailDump,
  sharepoint_dump: sharepointDump,
  teams_dump: teamsDump,
  vm_disk_download: vmDiskDownload,
  defender_plan_audit: defenderPlanAudit,
  defender_contact_audit: defenderContactAudit,
  storage_security_audit: storageSecurityAudit,
  sql_audit_config: sqlAuditConfig,
  postgres_audit: postgresAudit,
  mysql_audit: mysqlAudit,
  cosmos_security_audit: cosmosSecurityAudit,
  diagnostic_audit: diagnosticAudit,
  activity_alert_audit: activityAlertAudit,
  network_watcher_audit: networkWatcherAudit,
  vm_security_audit: vmSecurityAudit,
  appservice_security_audit: appserviceSecurityAudit,
  keyvault_security_audit: keyvaultSecurityAudit,
  identity_mfa_audit: identityMfaAudit,
  guest_access_audit: guestAccessAudit,
  password_policy_audit: passwordPolicyAudit,
  resource_lock_audit: resourceLockAudit,
  policy_compliance_audit: policyComplianceAudit,
  federation_backdoor: federationBackdoor,
  pta_abuse: ptaAbuse,
  aadconnect_dump: aadconnectDump,
  seamless_sso_abuse: seamlessSsoAbuse,
  saml_forge: samlForge,
  mfa_manipulation: mfaManipulation,
  user_creation: userCreation,
  password_spray: passwordSpray,
  tenant_recon_insider: tenantReconInsider,
  consent_phish: consentPhish,
  resource_hijack: resourceHijack,
  data_destroy: dataDestroy,
  ransomware_sim: ransomwareSim,
  account_lockout: accountLockout,
  service_disruption: serviceDisruption,
  exchange_abuse: exchangeAbuse,
  sharepoint_enum: sharepointEnum,
  teams_enum: teamsEnum,
  onedrive_access: onedriveAccess,
  cleanup_azure: cleanupAzure,
}

const CWE_MAP: Record<string, string> = {
  "AZ-SUB-001": "CWE-200",
  "AZ-RG-001": "CWE-200",
  "AZ-VNET-001": "CWE-284",
  "AZ-DNS-001": "CWE-693",
  "AZ-DNS-TAKEOVER": "CWE-672",
  "AZ-ACR-001": "CWE-522",
  "AZ-ACR-002": "CWE-284",
  "AZ-VMSS-001": "CWE-200",
  "AZ-REDIS-001": "CWE-319",
  "AZ-REDIS-002": "CWE-284",
  "AZ-ADF-001": "CWE-312",
  "AZ-FD-001": "CWE-693",
  "AZ-ACI-001": "CWE-312",
  "AZ-ENUM-001": "CWE-200",
  "AZ-ENUM-002": "CWE-200",
  "AZ-NSG-001": "CWE-284",
  "AZ-NSG-002": "CWE-284",
  "AZ-RBAC-001": "CWE-269",
  "AZ-RBAC-002": "CWE-269",
  "AZ-SQL-001": "CWE-284",
  "AZ-SQL-002": "CWE-319",
  "AZ-APPSVC-001": "CWE-312",
  "AZ-APPSVC-002": "CWE-522",
  "AZ-AKS-001": "CWE-522",
  "AZ-AKS-002": "CWE-284",
  "AZ-VM-001": "CWE-200",
  "AZ-VM-002": "CWE-284",
  "AZ-APIM-001": "CWE-200",
  "AZ-APIM-002": "CWE-312",
  "AZ-APIM-003": "CWE-522",
  "AZ-DBR-001": "CWE-200",
  "AZ-DBR-002": "CWE-200",
  "AZ-APPINS-001": "CWE-200",
  "AZ-APPINS-002": "CWE-522",
  "AZ-MON-001": "CWE-778",
  "AZ-MON-002": "CWE-778",
  "AZ-MON-003": "CWE-778",
  "AZ-RECOVERY-001": "CWE-693",
  "AZ-RECOVERY-002": "CWE-693",
  "AZ-INTUNE-001": "CWE-200",
  "AZ-INTUNE-002": "CWE-200",
  "AZ-INTUNE-003": "CWE-200",
  "AZ-USER-001": "CWE-200",
  "AZ-USER-002": "CWE-200",
  "AZ-APPREG-001": "CWE-269",
  "AZ-APPREG-002": "CWE-269",
  "AZ-APP-001": "CWE-522",
  "AZ-APP-002": "CWE-522",
  "AZ-APP-003": "CWE-269",
  "AZ-APP-004": "CWE-269",
  "AZ-CONNECTOR-001": "CWE-522",
  "AZ-RUNBOOK-001": "CWE-94",
  "AZ-RUNBOOK-002": "CWE-94",
  "AZ-SYNAPSE-001": "CWE-200",
  "AZ-SYNAPSE-002": "CWE-200",
  "AZ-PURVIEW-001": "CWE-200",
  "AZ-PURVIEW-002": "CWE-200",
  "AZ-SUBDOMAIN-001": "CWE-672",
  "AZ-STALE-001": "CWE-269",
  "AZ-STALE-002": "CWE-269",
  "AZ-EXPOSURE-001": "CWE-284",
  "AZ-EXPOSURE-002": "CWE-284",
  "AZ-EXPOSURE-003": "CWE-284",
  "AZ-DBR-SECRET-001": "CWE-522",
  "AZ-COG-001": "CWE-522",
  "AZ-COG-002": "CWE-522",
  "AZ-IOT-001": "CWE-522",
  "AZ-SIGNALR-001": "CWE-200",
  "AZ-SIGNALR-002": "CWE-200",
  "AZ-EVGRID-001": "CWE-200",
  "AZ-BATCH-001": "CWE-200",
  "AZ-BATCH-002": "CWE-200",
  "AZ-BATCH-003": "CWE-200",
  "AZ-BATCH-004": "CWE-200",
  "AZ-MAPS-001": "CWE-522",
  "AZ-SENTINEL-ENUM-001": "CWE-200",
  "AZ-VPN-001": "CWE-200",
  "AZ-VPN-002": "CWE-200",
  "AZ-ER-001": "CWE-200",
  "AZ-ER-002": "CWE-200",
  "AZ-PL-001": "CWE-284",
  "AZ-SF-001": "CWE-200",
  "AZ-BATCHACCT-001": "CWE-200",
  "AZ-MANAGEDENV-001": "CWE-200",
  "AZ-STATICWEB-001": "CWE-200",
  "AZ-KV-001": "CWE-522",
  "AZ-KV-002": "CWE-522",
  "AZ-MI-001": "CWE-522",
  "AZ-IMDS-001": "CWE-522",
  "AZ-TOKEN-001": "CWE-522",
  "AZ-TOKEN-002": "CWE-312",
  "AZ-CRED-001": "CWE-522",
  "AZ-CRED-002": "CWE-522",
  "AZ-CERT-001": "CWE-522",
  "AZ-SKEY-001": "CWE-522",
  "AZ-SKEY-002": "CWE-320",
  "AZ-AUTO-001": "CWE-522",
  "AZ-AUTO-002": "CWE-312",
  "AZ-GRAPHTOKEN-001": "CWE-522",
  "AZ-REFRESH-001": "CWE-613",
  "AZ-RUNBOOK-CRED-001": "CWE-798",
  "AZ-KUBE-001": "CWE-522",
  "AZ-KUBE-002": "CWE-522",
  "AZ-KUBE-003": "CWE-522",
  "AZ-WEBAPP-ENV-001": "CWE-312",
  "AZ-WEBAPP-ENV-002": "CWE-798",
  "AZ-PRIVESC-001": "CWE-269",
  "AZ-ROLE-001": "CWE-269",
  "AZ-ROLE-002": "CWE-732",
  "AZ-CA-001": "CWE-287",
  "AZ-CA-002": "CWE-287",
  "AZ-PIM-001": "CWE-269",
  "AZ-PIM-002": "CWE-269",
  "AZ-MI-PRIV-001": "CWE-269",
  "AZ-DEPLOY-001": "CWE-269",
  "AZ-GLOBALADMIN-001": "CWE-269",
  "AZ-APPADMIN-001": "CWE-269",
  "AZ-HIERARCHY-001": "CWE-269",
  "AZ-DYNGROUP-001": "CWE-269",
  "AZ-PARTNER-001": "CWE-284",
  "AZ-PERSIST-001": "CWE-547",
  "AZ-PERSIST-002": "CWE-547",
  "AZ-PERSIST-003": "CWE-547",
  "AZ-EXT-001": "CWE-94",
  "AZ-WEBHOOK-001": "CWE-547",
  "AZ-DEVOPS-001": "CWE-94",
  "AZ-LH-001": "CWE-284",
  "AZ-ACRBACKDOOR-001": "CWE-506",
  "AZ-SCHEDTASK-001": "CWE-547",
  "AZ-OAUTHPERSIST-001": "CWE-547",
  "AZ-RUNCMD-001": "CWE-78",
  "AZ-RUNCMD-002": "CWE-78",
  "AZ-BASTION-001": "CWE-284",
  "AZ-ARC-001": "CWE-78",
  "AZ-SVCCONN-001": "CWE-522",
  "AZ-XTENANT-001": "CWE-284",
  "AZ-CSEXT-001": "CWE-94",
  "AZ-USERDATA-001": "CWE-94",
  "AZ-INTUNE-DEPLOY-001": "CWE-94",
  "AZ-MSBUILD-001": "CWE-94",
  "AZ-SHAREDIMG-001": "CWE-506",
  "AZ-DIAG-001": "CWE-778",
  "AZ-DIAG-002": "CWE-778",
  "AZ-SENTINEL-001": "CWE-778",
  "AZ-SENTINEL-002": "CWE-693",
  "AZ-DEFENDER-001": "CWE-693",
  "AZ-DEFENDER-002": "CWE-693",
  "AZ-ACTLOG-001": "CWE-778",
  "AZ-ACTLOG-002": "CWE-778",
  "AZ-POLICY-001": "CWE-693",
  "AZ-WAF-001": "CWE-693",
  "AZ-WAF-002": "CWE-693",
  "AZ-ALERT-001": "CWE-778",
  "AZ-ALERT-002": "CWE-778",
  "AZ-LOGANALYTICS-001": "CWE-778",
  "AZ-NSGFLOW-001": "CWE-778",
  "AZ-RESMOVE-001": "CWE-693",
  "AZ-TAG-001": "CWE-693",
  "AZ-STORAGE-001": "CWE-200",
  "AZ-STORAGE-002": "CWE-200",
  "AZ-COSMOS-001": "CWE-200",
  "AZ-DISK-001": "CWE-200",
  "AZ-DISK-002": "CWE-200",
  "AZ-DISK-003": "CWE-200",
  "AZ-TABLE-001": "CWE-200",
  "AZ-QUEUE-001": "CWE-200",
  "AZ-FILESHARE-001": "CWE-200",
  "AZ-DATALAKE-001": "CWE-200",
  "AZ-SBUS-001": "CWE-200",
  "AZ-EHUB-001": "CWE-200",
  "AZ-MAIL-001": "CWE-200",
  "AZ-MAIL-002": "CWE-506",
  "AZ-SP-001": "CWE-200",
  "AZ-SP-002": "CWE-200",
  "AZ-SP-003": "CWE-200",
  "AZ-TEAMS-001": "CWE-200",
  "AZ-TEAMS-002": "CWE-200",
  "AZ-TEAMS-003": "CWE-200",
  "AZ-TEAMS-004": "CWE-200",
  "AZ-VMDISK-001": "CWE-200",
  "AZ-CIS-DEFENDER-001": "CWE-693",
  "AZ-CIS-CONTACT-001": "CWE-778",
  "AZ-CIS-STORAGE-001": "CWE-319",
  "AZ-CIS-SQL-001": "CWE-778",
  "AZ-CIS-PG-001": "CWE-319",
  "AZ-CIS-MYSQL-001": "CWE-319",
  "AZ-CIS-COSMOS-001": "CWE-284",
  "AZ-CIS-DIAG-001": "CWE-778",
  "AZ-CIS-ALERT-001": "CWE-778",
  "AZ-CIS-NW-001": "CWE-778",
  "AZ-CIS-VM-001": "CWE-311",
  "AZ-CIS-APPSVC-001": "CWE-319",
  "AZ-CIS-KV-001": "CWE-693",
  "AZ-CIS-MFA-001": "CWE-287",
  "AZ-CIS-GUEST-001": "CWE-284",
  "AZ-CIS-PWD-001": "CWE-521",
  "AZ-CIS-LOCK-001": "CWE-693",
  "AZ-CIS-POLICY-001": "CWE-693",
  "AZ-FED-001": "CWE-284",
  "AZ-FED-002": "CWE-284",
  "AZ-PTA-001": "CWE-522",
  "AZ-PTA-002": "CWE-200",
  "AZ-AADC-001": "CWE-522",
  "AZ-AADC-002": "CWE-269",
  "AZ-AADC-003": "CWE-269",
  "AZ-SSO-001": "CWE-522",
  "AZ-SSO-002": "CWE-522",
  "AZ-SAML-001": "CWE-522",
  "AZ-MFA-001": "CWE-308",
  "AZ-MFA-002": "CWE-308",
  "AZ-MFA-003": "CWE-287",
  "AZ-SPRAY-001": "CWE-521",
  "AZ-SPRAY-002": "CWE-521",
  "AZ-TENANT-001": "CWE-284",
  "AZ-TENANT-002": "CWE-269",
  "AZ-CONSENT-001": "CWE-284",
  "AZ-CONSENT-002": "CWE-863",
  "AZ-HIJACK-001": "CWE-269",
  "AZ-DESTROY-001": "CWE-400",
  "AZ-RANSOM-001": "CWE-400",
  "AZ-LOCKOUT-001": "CWE-307",
  "AZ-DISRUPT-001": "CWE-400",
  "AZ-EXCHANGE-001": "CWE-200",
  "AZ-EXCHANGE-002": "CWE-284",
  "AZ-SHAREPOINT-001": "CWE-200",
  "AZ-TEAMS-ENUM-001": "CWE-200",
  "AZ-ONEDRIVE-001": "CWE-200",
  "AZ-CLEANUP-001": "CWE-1254",
}

const NO_CLI_PROGRAMS = new Set<string>([
  "managed_identity",
  "imds_harvest",
  "token_theft",
  "device_code_phish",
  "password_spray",
])

const programKeys = Object.keys(PROGRAMS) as [Program, ...Program[]]

export const AzurehookTool = Tool.define("azurehook", {
  description: `Execute an Azure post-exploitation program. 154 programs across 13 categories: recon (47), credential (14), privesc (11), persistence (11), lateral (10), evasion (11), exfil (12), compliance (18), identity (10), impact (5), m365 (4), cleanup (1). Uses az CLI and Azure REST API. Available: ${programKeys.join(", ")}. ALWAYS run cleanup_azure before leaving.`,
  parameters: z.object({
    program: z.enum(programKeys).describe(
      "Azure program to execute. Options: " +
        Object.entries(PROGRAMS)
          .map(([k, v]) => `${k} — ${v.description}`)
          .join("; "),
    ),
    args: z.array(z.string()).describe("Arguments to pass to the program"),
    timeout_seconds: z.number().optional().default(300).describe("Maximum execution time in seconds (default: 300)"),
  }),
  async execute(params) {
    if (!Bun.which("az") && !NO_CLI_PROGRAMS.has(params.program)) {
      return {
        title: `azurehook: ${params.program}`,
        output: "az CLI not found. Install: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli",
        metadata: { program: params.program, findings: [] as Finding[] },
      }
    }

    const program = params.program as Program
    const handler = dispatch[program]
    let result: HookResult
    try {
      result = await handler(params.args, params.timeout_seconds)
    } catch (e) {
      return {
        title: `azurehook: ${program}`,
        output: `[-] ${program} failed: ${e instanceof Error ? e.message : String(e)}`,
        metadata: { program, findings: [] as Finding[] },
      }
    }

    const enriched = result.findings.map((f) => {
      const cwe = CWE_MAP[f.checkId]
      return cwe ? { ...f, cwe } : f
    })

    return {
      title: `azurehook: ${program}`,
      output: result.output,
      metadata: { program, findings: enriched },
    }
  },
})
